#!/bin/bash

# Check for the required number of arguments
if [ $# -lt 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# Define variables from arguments
file_path="$1"
server_ip="$2"
username="$3"
ssh_key="$4"
