#!/usr/bin/env bash
# performing a 301 moved permanently

sudo apt-get update
sudo apt-get install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
string_repl="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/gabamazing21\/ 301;"

sed -i "s/server_name _;/$string_repl/" /etc/nginx/site-enabled/default

sudo service nginx restart
