#!/usr/bin/env bash
# track several signal event
echo $$ > /var/run/myscript.pid.tmp
trap 'sigterm_exit' SIGTERM
trap 'sigint'  SIGINT
trap 'remove_pid_and_exit' SIGQUIT
remove_pid_and_exit()
{
	rm -f /var/run/myscript.pid /var/run/myscript.pid.tmp
	exit 0
	
}
sigint()
{
	echo "Y U no love me?!"
	exit 0
}

sigterm_exit()
{
	echo "I hate the kill command"
	remove_pid_and_exit
}
mv /var/run/myscript.pid.tmp /var/run/myscript.pid
while true; do
	echo "To infinity and beyond"
done
