#!/usr/bin/env bash
#fizzbuzz
counter=1
while [ $counter -lt 100 ]; do

	if [ $((counter % 5)) -eq 0 ] && [ $((counter % 3)) -eq 0 ]; then
		echo "FizzBuzz"
	elif [ $((counter % 3)) -eq 0 ]; then
		echo "Fizz"
	elif [ $((counter % 5)) -eq 0 ]; then
		echo "Buzz"
	else
		echo "$counter"
	fi
	((counter++))
done
