#!/usr/bin/env bash
#print /etc/passwd in professional
IFS=$'\n'
while IFS=: read -r username password uid gid uid_info home_dir command
do
	echo "The user $username is part of the $gid gang, lives in $home_dir and rides $command. $uid place is protected by the passcode $password, more info about the user here: $uid_info"
done < /etc/passwd
