#!/usr/bin/env bash
#Superstitious numbers
counter=1
while [ $counter -lt 21 ]; do
	if [ $counter -eq 4 ]; then
		echo "bad luck from China"
	elif [ $counter -eq 9 ]; then
		echo "bad luck from Japan"
	elif [ $counter -eq 17 ]; then
		echo "bad luck from Italy"
	else
		echo "$counter"
	fi
	((counter++))
done
