#!/usr/bin/env bash
# 12 hour clock project
counter_minute=1
counter_hour=0
while [ $counter_hour -lt 12 ]; do
	echo "Hour: $counter_hour"
	while [ $counter_minute -lt 60 ]; do
		echo "$counter_minute"
		((counter_minute++))
	done
	((counter_minute=1))
	((counter_hour++))
done
