#!/usr/bin/env bash
# 12 hour clock
counter_minute=1
counter_hour=0
echo "Hour: $counter_hour"
while [ $counter_hour -lt 12 ]; do
	if [ $counter_minute -eq 60 ]; then
		((counter_hour++))
		echo "Hour: $counter_hour"
		((counter_minute=1))
	else
		echo "$counter_minute"
	((counter_minute++))
	fi
done
